### ISSUE TITLE
Проверка бустинг

### ISSUE THREAD

**Issue by KochetovNicolai** [PaulZakharov/MY_DMIA#1]
Привет!

1. Ошибка в строчке 
`grad = -original_y/(1+math.exp(np.dot(original_y, pred_y)))`
должно быть 
`grad = -original_y/(1+math.exp(original_y * pred_y))`
В первом случае получается скалярное произведение, во втором - поэлементное. В задании написано, что градиент вычисляем на каждом объекте.

2. Судя по строкам `estimator.fit(X, grad)` и `y_pred += self.lr*est.predict(X)`, бустинг идет в направление градиента, то есть максимизирует функцию потерь, а затем отвечает противоположенным классом (`-1 if pred >= 0.5 else 1`). В общем случае это не тот же классификатор, который минимизирует функцию потерь.

3. `-1 if pred >= 0.5 else 1` - казалось бы, классы - это значения 1 и -1, и сравнивать логично с 0, а не с 0.5

4. Оценивать качество на обучающей выборке, в целом, не`очень разумная идея. Можно не заметить переобучение. Нужно сделать кросс-валидацию (функция cross_val_score).

Пока засчитываю частично. Есть возможность исправить.

**Comment by PaulZakharov** [comment]
Спасибо за комментарии. Починил

**Comment by KochetovNicolai** [comment]
Хорошо! Засчитываю.
